### ISSUE TITLE
New front page look

### ISSUE THREAD

**Issue by shannonwells** [shannonwells/clickbait_generator#19]
![desktop hd](https://cloud.githubusercontent.com/assets/502640/22124651/908fe5c0-de45-11e6-88c7-74c81937b80e.png)

    __- [ ] grab a creative-commons photo from Flickr with a specific tag __ NOPE
- [ ] top navbar/sharing links
- [ ] better appearance at different breakpoints - max width on buttons, minimum padding, reduced font size at mobile

**Comment by shannonwells** [comment]
First pass:  #21 merged PR

**Comment by bunnymatic** [comment]
a tiny bit of styling of the header and the share permalink button is included in the candy button PR #22 
it might be worth stealing from there if that PR were to not get merged.
