### ISSUE TITLE
italic "whatever" needs space around it in the bait

### ISSUE THREAD

**Issue by bunnymatic** [shannonwells/clickbait_generator#26]
<img width="623" alt="screen shot 2017-02-14 at 12 29 28 pm" src="https://cloud.githubusercontent.com/assets/427380/22957592/4d618878-f2f7-11e6-9ad6-e62eb6ab4566.png">

I don't know where that _whatever_ get's jammed in but it needs a space on the right hand side.

Saw it a couple times today.

**Comment by shannonwells** [comment]
I only see the word "whatever" in tests

**Comment by bunnymatic** [comment]
weird
